import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const skill=read('SKILL.md'),recipes=read('references/operation-recipes.md');
const samples=[...recipes.matchAll(/```json\s*\n([\s\S]*?)\n```/g)].map(x=>JSON.parse(x[1]));
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.name==='.git'||x.name==='node_modules'?[]:x.isDirectory()?walk(path.join(dir,x.name)):[path.join(dir,x.name)]);
const docs=walk(root).filter(f=>/\.md$/.test(f));

test('v6 entry is a compact MCP-first Skill',()=>{assert.match(skill,/version: 6\.0\.0/);assert.ok(skill.split('\n').length<=100);assert.ok(Buffer.byteLength(skill)<15000);assert.match(skill,/优先使用 MCP/);});
test('approved schematic remains input without upstream review',()=>{assert.match(skill,/approved_schematic/);assert.match(skill,/不重新开展选型/);assert.match(skill,/也不把这些事项延后/);});
test('AI owns design and analysis timing',()=>{assert.match(skill,/AI 决定功能分区/);assert.match(skill,/不作布局许可或设计评分/);assert.match(skill,/按需调用/);assert.match(skill,/具体时机由任务需要决定/);});
test('common operations do not fall through to handwritten APIs',()=>{assert.match(skill,/常见操作直接调用对应 PCB MCP/);assert.match(skill,/补进 MCP 后恢复简化接口/);assert.match(skill,/不要求人为制造一次失败调用/);});
test('bulk requests have no public tiny-batch or guarded plan prerequisite',()=>{assert.match(skill,/无需 mode、prepare、guard、expected、批次上限或旧对象/);assert.match(skill,/可一次布局整板/);assert.match(skill,/未填写字段保持原值/);assert.doesNotMatch(skill,/不超过 100|单批上限|prepare → execute|LAYOUT_DRC|padOverlapGate/);});
test('orientation and dimensions separate factual sources',()=>{const d=read('references/data-feedback.md');for(const term of ['poseLocal','body','assembly','silkscreen','padEnvelope','当前板面已有镜像','resultId'])assert.ok(d.includes(term),term);assert.match(d,/coverage.atomic=false/);});
test('SVG labels stay separate from native silkscreen',()=>{assert.match(skill,/SVG 标注只是观察叠加/);assert.match(read('references/data-feedback.md'),/不会写入 PCB 丝印/);assert.match(read('references/silkscreen-usability.md'),/保留属性和 BOM 身份/);});
test('DRC data reports completed state and honest totals, never permission',()=>{const p=read('references/drc-policy.md');for(const term of ['RUNNING','drcJobId','drcVerified','drcErrorCount','空明细页','同网络','可信封装','未连接'])assert.ok(p.includes(term),term);assert.match(p,/不批准布局/);assert.doesNotMatch(p,/必须运行四类阶段门|下一轮.*不允许/);});
test('design knowledge remains available',()=>{const design=skill+read('references/placement-routing-closure.md')+read('references/experimental/motor-foc.md');for(const term of ['自举','Kelvin','ADC','整组','返回','铜颈','接口','高 dv/dt'])assert.ok(design.includes(term),term);});
test('user changes and unknown outcomes are preserved',()=>{assert.match(skill,/保留最新人工位置/);assert.match(skill,/不能盲目重放/);assert.match(skill,/不能把 unknown 当作未写入/);assert.match(skill,/明确权限拒绝不换入口绕过/);});
test('documentation-only work does not write a production PCB',()=>{assert.match(skill,/不为验收改动正在工作的 PCB/);assert.match(read('references/verification-contract.md'),/模拟写入与真实板写入分别报告/);});
test('examples cover common native wrappers with compact requests',()=>{assert.equal(samples.length,6);const operations=samples.flatMap(x=>x.operations);for(const op of ['place','route','via','outline','hole','region','pad','fill','pour','align','distribute','radial','transform','modify','delete','text','cleanup'])assert.ok(operations.some(x=>x.op===op),op);for(const sample of samples){assert.equal(sample.guard,undefined);assert.equal(sample.mode,undefined);assert.equal(sample.expected,undefined);assert.ok(sample.operations.length);}});
test('examples validate against the colocated MCP v3 types when installed together',async t=>{const modulePath=process.env.EASYEDA_PCB_MCP_ROOT?path.join(process.env.EASYEDA_PCB_MCP_ROOT,'src/simple-contract.mjs'):path.resolve(root,'../../mcp/easyeda-pcb/src/simple-contract.mjs');if(!fs.existsSync(modulePath)){t.skip('Standalone Skill checkout: set EASYEDA_PCB_MCP_ROOT for integrated schema validation');return;}const {operation,expandOperations}=await import(pathToFileURL(modulePath).href);for(const s of samples){const parsed=s.operations.map(x=>operation.parse(x));assert.ok(expandOperations(parsed).length>=parsed.length);}});
test('every relative Markdown link resolves inside the Skill package',()=>{for(const f of docs)for(const m of fs.readFileSync(f,'utf8').matchAll(/\[[^\]]*\]\(([^)]+)\)/g)){const ref=m[1].split('#')[0];if(!ref||/^[a-z][a-z0-9+.-]*:/i.test(ref))continue;const dest=path.resolve(path.dirname(f),ref);assert.ok(dest.startsWith(root+path.sep),`${f}: ${ref}`);assert.ok(fs.existsSync(dest),`${f}: ${ref}`);}});
test('portable core does not embed a particular board or host',()=>{const core=skill+recipes+read('templates/progress-first-task-prompt.md');assert.doesNotMatch(core,/4310|QDrive|[A-Z]:\\Users\\|[A-Z]:\\PROJECT\\|~\/.agentdock/);assert.match(core,/本任务/);});
test('default tool index reflects the v3 surface',()=>{const doc=read('references/tool-index.md');assert.match(doc,/MCP 3\.0\.0/);assert.match(doc,/默认21工具/);const names=[...doc.matchAll(/\| `(pcb_[a-z_]+)` \|/g)].map(x=>x[1]);assert.equal(new Set(names).size,21);assert.ok(names.includes('pcb_execute_plan'));assert.ok(names.includes('pcb_read'));});
